In [3]:
import numpy as np

sample_data = """>Rosalind_1
ATCCAGCT
>Rosalind_2
GGGCAACT
>Rosalind_3
ATGGATCT
>Rosalind_4
AAGCAACC
>Rosalind_5
TTGGAACT
>Rosalind_6
ATGCCATT
>Rosalind_7
ATGGCACT """



In [4]:
chunks = []  # create an empty list to store extracted data

start = 0  # initialize start variable to 0
while True:  # create a loop that continues until broken
    start = sample_data.find(">", start)  # find the next ">" symbol in data starting from the current value of start
    if start == -1:  # if ">" symbol is not found, break the loop
        break
    end = sample_data.find(">", start+1)  # find the next ">" symbol after the start symbol in data
    if end == -1:  # if ">" symbol is not found, set end to the length of text
        end = len(sample_data)
    piece = sample_data[start+1:end].strip()  # extract the text between the two ">" symbols and remove any leading/trailing whitespaces
    chunks.append(piece)  # add the extracted piece to the chunks list
    start = end  # set the start value to the end value for the next iteration of the loop

chunks = [chunk.replace('\n', ' ') for chunk in chunks]    


# Define an empty list to store the names
list_item_names = []
list_item_sequence = []

# Iterate over each item in the list
for item in chunks:
    # Split the item by the first space character
    name, sequence = item.split(' ', 1)
    # Append the name to the list_item_names list
    list_item_names.append(name)

for item in chunks:
    # Split the item by the first space character
    name, sequence = item.split(' ', 1)
    # Append the name to the list_item_names list
    list_item_sequence.append(sequence)        
        
my_dict = dict(zip(list_item_names, list_item_sequence))

print(my_dict)

{'Rosalind_1': 'ATCCAGCT', 'Rosalind_2': 'GGGCAACT', 'Rosalind_3': 'ATGGATCT', 'Rosalind_4': 'AAGCAACC', 'Rosalind_5': 'TTGGAACT', 'Rosalind_6': 'ATGCCATT', 'Rosalind_7': 'ATGGCACT'}


In [5]:
# Get the lengths of the strings in the values of the dictionary
string_lengths = [len(s) for s in my_dict.values()]

# Create the grid with the appropriate shape
grid = np.zeros((len(my_dict), max(string_lengths)))

print(grid)


[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [36]:
i = 1

for key in my_dict:
    grab = my_dict[key]
    print(i, grab)
    i = i + 1
    
    for seq in grab:
        print(seq)
    
 
        
 

1 ATCCAGCT
A
T
C
C
A
G
C
T
2 GGGCAACT
G
G
G
C
A
A
C
T
3 ATGGATCT
A
T
G
G
A
T
C
T
4 AAGCAACC
A
A
G
C
A
A
C
C
5 TTGGAACT
T
T
G
G
A
A
C
T
6 ATGCCATT
A
T
G
C
C
A
T
T
7 ATGGCACT
A
T
G
G
C
A
C
T


In [13]:
grid2 = np.zeros((2,2))
print(grid2)

[[0. 0.]
 [0. 0.]]
